### ISSUE TITLE
Contract exports more than ("main") and ("memory").

### ISSUE THREAD

**Issue by oracle3** [poemm/C_ewasm_contracts#2]
When I compiled C code wasm, I had several more export symbols:
(export "memory" (memory 0))
(export "_heap_base" (global 1))
(export "_data_end" (global 2))
(export "_main" (func $_main))
Errors occurred during execution:
Contract exports more than ("main") and ("memory").
How to remove redundant export symbols? I didn't see any effect using chisel run

**Comment by poemm** [comment]
I never claimed that there are no awkward parts.

The exports `heap_base` and `data_end` must be removed, export `_main` should be renamed to `main`, and imports should be from module `ethereum` instead of `env`. This is automated in [here](https://github.com/poemm/C_ewasm_contracts/blob/c2d95ee80a2ddeeecb614e1ba8d96da7dcb55b56/Makefile#L132), although you can also use sed as follows.

```
# generate file.wat with Wabt's wasm2wat, then:
sed -i -e 's/"env"/"ethereum"/g' file.wat
sed -i -e 's/"_main"/"main"/g' file.wat
sed -i '/_heap_base/d' file.wat
sed -i '/_data_end/d' file.wat
```

**Comment by oracle3** [comment]
thanks
